### ISSUE TITLE
Setup initial repo files in all StateMod Python repos

### ISSUE THREAD

**Issue by smalers** [OpenCDSS/cdss-app-statemod-python#1]
The statemod*-python repositories needs to be set up with normal .gitignore, .gitattributes, LICENSE.md and README.md.  Make sure to use .gitignore that is suitable for Python (see the GeoProcessor).

I recommend using a run script to start PyCharm, similar to GeoProcessor.  However, in this case we are NOT using the QGIS Pythons so initialize a virtual environment for PyCharm using Python 3.x installed on the computer.

Keep separate repos for the code for now, to be consistent with Java and C#.

**Comment by jurentie** [comment]
Added initial repo files in all statemod python repos
