### ISSUE TITLE
Enumeration classes

### ISSUE THREAD

**Issue by jurentie** [OpenCDSS/cdss-app-statemod-python#3]
I need to put more research into enumerations in general. I need to understand better the enumeration class in Java so that I can convert this class to Python. `StateModRunModeType.py` needs to be converted to Python. I have substituted a generic solution so that `StateModRunModeType` is not needed in the main class, for now. 
ex:
```python
                if arg.upper() == "-BASEFLOWS" or arg.upper() == "--BASEFLOWS":
                    #runMode = StateModRunModType.BASEFLOWS
                    runMode = "BASEFLOWS"
                    pass
                if arg.upper() == "-CHECK" or arg.upper() == "--CHECK":
                    #runMode = StateModRunModeType.CHECK
                    runMode = "CHECK"
                    pass
                ...
                elif arg.upper() == "-SIM" or arg.upper() == "--SIM":
                    #runMode = StateModRunModeType.SIMULATE
                    runMode = "SIMULATE"
                    pass
```

**Comment by jurentie** [comment]
`YearType.py` also needs enumerated. For now in `StateMod_DataSet.py`  `__cyrl = "Calendar"` when it should b `__cyrl = YearType.CALENDAR`

**Comment by smalers** [comment]
I implemented enumerations where it made sense.  Close this issue.
